# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 05:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('Inc_ID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Inc_date', models.DateTimeField(verbose_name='date of incident')),
                ('Veh_Miles_Begin', models.PositiveIntegerField(default=0)),
                ('Veh_Miles_End', models.PositiveIntegerField(default=0)),
                ('Inc_Lat', models.IntegerField(default=0)),
                ('Inc_Long', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('Veh_ID', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('Agency', models.CharField(max_length=200)),
                ('Available', models.BooleanField(default=True)),
                ('Veh_Lat', models.IntegerField(default=0)),
                ('Veh_Long', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='dispatch',
            name='Veh_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ems.Vehicle'),
        ),
    ]
