# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch',
            name='Inc_Lat',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='Inc_Long',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='Veh_Lat',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='Veh_Long',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=7),
        ),
    ]
